### ISSUE TITLE
Allow double clicking to reset controls

### ISSUE THREAD

**Issue by tesselode** [nimbletools/misstortion#1]

**Comment by codecat** [comment]
Good idea! Though I would prefer middle-clicking myself, since left clicking a slider already means you're putting the value at the point where you're clicking.

**Comment by tesselode** [comment]
i suppose, but double clicking is the most standard for audio plugins, and it's easier for people using touchpads on their laptops. ctrl+click is ok too, but then you have to have one hand on the keyboard
